export default `
<!-- saved from url=(0029)https://news.ycombinator.com/ -->
<html op="news"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="./Hacker News_files/news.css">
        <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
          <link rel="alternate" type="application/rss+xml" title="RSS" href="https://news.ycombinator.com/rss">
        <title>Hacker News</title></head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
        <tbody><tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tbody><tr><td style="width:18px;padding-right:4px"><a href="https://news.ycombinator.com/"><img src="./Hacker News_files/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
                  <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="https://news.ycombinator.com/news">Hacker News</a></b>
              <a href="https://news.ycombinator.com/newest">new</a> | <a href="https://news.ycombinator.com/threads?id=joshwarwick15">threads</a> | <a href="https://news.ycombinator.com/front">past</a> | <a href="https://news.ycombinator.com/newcomments">comments</a> | <a href="https://news.ycombinator.com/ask">ask</a> | <a href="https://news.ycombinator.com/show">show</a> | <a href="https://news.ycombinator.com/jobs">jobs</a> | <a href="https://news.ycombinator.com/submit">submit</a>            </span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop">
                              <a id="me" href="https://news.ycombinator.com/user?id=joshwarwick15">joshwarwick15</a>                (1) |
                <a id="logout" href="https://news.ycombinator.com/logout?auth=9ed2752edc77b57b6883022a1ca6b49b80087f52&amp;goto=news">logout</a>                          </span></td>
              </tr></tbody></table></td></tr>
<tr id="pagespace" title="" style="height:10px"></tr><tr><td><table border="0" cellpadding="0" cellspacing="0" class="itemlist">
              <tbody><tr class="athing" id="22334715">
      <td align="right" valign="top" class="title"><span class="rank">1.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22334715" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22334715&amp;how=up&amp;auth=5b97970ace5f8769baebbd5cd012d308a4da9c57&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://back-on-track.eu/more-emphasis-on-trains-in-europe-to-replace-flights/" class="storylink">More emphasis on trains in Europe to replace flights</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=back-on-track.eu"><span class="sitestr">back-on-track.eu</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22334715">67 points</span> by <a href="https://news.ycombinator.com/user?id=edward" class="hnuser">edward</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22334715">45 minutes ago</a></span> <span id="unv_22334715"></span> | <a href="https://news.ycombinator.com/hide?id=22334715&amp;auth=5b97970ace5f8769baebbd5cd012d308a4da9c57&amp;goto=news" onclick="return hidestory(event, this, 22334715)">hide</a> | <a href="https://news.ycombinator.com/item?id=22334715">58&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22334702">
      <td align="right" valign="top" class="title"><span class="rank">2.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22334702" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22334702&amp;how=up&amp;auth=19f63a4d4adc10030b88d2b360de8098a504a0ee&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://docs.google.com/spreadsheets/d/1-xIgk7Mw1S5DXTZSbKBgxlsQAn7XGIu7Mfy72lSVHKk/edit#gid=129993618" class="storylink">Developer salary spreadsheet compiled from tweets</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=docs.google.com"><span class="sitestr">docs.google.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22334702">24 points</span> by <a href="https://news.ycombinator.com/user?id=ollieglass" class="hnuser">ollieglass</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22334702">49 minutes ago</a></span> <span id="unv_22334702"></span> | <a href="https://news.ycombinator.com/hide?id=22334702&amp;auth=19f63a4d4adc10030b88d2b360de8098a504a0ee&amp;goto=news" onclick="return hidestory(event, this, 22334702)">hide</a> | <a href="https://news.ycombinator.com/item?id=22334702">6&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22333994">
      <td align="right" valign="top" class="title"><span class="rank">3.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22333994" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22333994&amp;how=up&amp;auth=fbeaccbd2f11c53404cd50f34cfafe61655222a1&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://homehack.nl/activitypub-the-secret-weapon-of-the-fediverse/" class="storylink">ActivityPub – The Secret Weapon of the Fediverse</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=homehack.nl"><span class="sitestr">homehack.nl</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22333994">139 points</span> by <a href="https://news.ycombinator.com/user?id=app4soft" class="hnuser">app4soft</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22333994">4 hours ago</a></span> <span id="unv_22333994"></span> | <a href="https://news.ycombinator.com/hide?id=22333994&amp;auth=fbeaccbd2f11c53404cd50f34cfafe61655222a1&amp;goto=news" onclick="return hidestory(event, this, 22333994)">hide</a> | <a href="https://news.ycombinator.com/item?id=22333994">58&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22334236">
      <td align="right" valign="top" class="title"><span class="rank">4.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22334236" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22334236&amp;how=up&amp;auth=3032b6ef39c720a242d02c5a59430bfc840af02d&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://www.japantimes.co.jp/news/2020/02/14/national/wakayama-positive-coronavirus/#.Xke6CjWIZTs" class="storylink">From Tokyo to Wakayama to Okinawa, Japan on Edge as Covid-19 Spreads</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=japantimes.co.jp"><span class="sitestr">japantimes.co.jp</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22334236">46 points</span> by <a href="https://news.ycombinator.com/user?id=fspeech" class="hnuser">fspeech</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22334236">3 hours ago</a></span> <span id="unv_22334236"></span> | <a href="https://news.ycombinator.com/hide?id=22334236&amp;auth=3032b6ef39c720a242d02c5a59430bfc840af02d&amp;goto=news" onclick="return hidestory(event, this, 22334236)">hide</a> | <a href="https://news.ycombinator.com/item?id=22334236">34&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22334446">
      <td align="right" valign="top" class="title"><span class="rank">5.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22334446" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22334446&amp;how=up&amp;auth=4ff7abf1d0890f3f26a015cc17770264c1b5bcbc&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://www.qt.io/blog/qt-5.15-alpha-released#commento" class="storylink">Qt 5.15 Alpha Released</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=qt.io"><span class="sitestr">qt.io</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22334446">25 points</span> by <a href="https://news.ycombinator.com/user?id=turrini" class="hnuser">turrini</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22334446">2 hours ago</a></span> <span id="unv_22334446"></span> | <a href="https://news.ycombinator.com/hide?id=22334446&amp;auth=4ff7abf1d0890f3f26a015cc17770264c1b5bcbc&amp;goto=news" onclick="return hidestory(event, this, 22334446)">hide</a> | <a href="https://news.ycombinator.com/item?id=22334446">1&nbsp;comment</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22331238">
      <td align="right" valign="top" class="title"><span class="rank">6.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22331238" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22331238&amp;how=up&amp;auth=80bcf8eb95bca00bf86fb3f968405b64a9f31422&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://www.wsj.com/articles/google-cuts-jobs-at-cloud-computing-group-11581719153" class="storylink">Google cuts jobs at cloud-computing group</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=wsj.com"><span class="sitestr">wsj.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22331238">411 points</span> by <a href="https://news.ycombinator.com/user?id=pgodzin" class="hnuser">pgodzin</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22331238">13 hours ago</a></span> <span id="unv_22331238"></span> | <a href="https://news.ycombinator.com/hide?id=22331238&amp;auth=80bcf8eb95bca00bf86fb3f968405b64a9f31422&amp;goto=news" onclick="return hidestory(event, this, 22331238)">hide</a> | <a href="https://news.ycombinator.com/item?id=22331238">257&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22334676">
      <td align="right" valign="top" class="title"><span class="rank">7.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22334676" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22334676&amp;how=up&amp;auth=221bd8867ca9baf7e0a1462135825cfd2b94d71b&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://caseyhandmer.wordpress.com/2020/02/15/dont-stage-off-starship/" class="storylink" rel="nofollow">Don’t Stage Off Starship</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=caseyhandmer.wordpress.com"><span class="sitestr">caseyhandmer.wordpress.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22334676">6 points</span> by <a href="https://news.ycombinator.com/user?id=davedx" class="hnuser">davedx</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22334676">56 minutes ago</a></span> <span id="unv_22334676"></span> | <a href="https://news.ycombinator.com/hide?id=22334676&amp;auth=221bd8867ca9baf7e0a1462135825cfd2b94d71b&amp;goto=news" onclick="return hidestory(event, this, 22334676)">hide</a> | <a href="https://news.ycombinator.com/item?id=22334676">discuss</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22334290">
      <td align="right" valign="top" class="title"><span class="rank">8.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22334290" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22334290&amp;how=up&amp;auth=6b49e642011c91dfcb2710541073f2657e54baa4&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://blogs.scientificamerican.com/cross-check/the-cancer-industry-hype-vs-reality/" class="storylink">The Cancer Industry: Hype vs. Reality</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=scientificamerican.com"><span class="sitestr">scientificamerican.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22334290">36 points</span> by <a href="https://news.ycombinator.com/user?id=jwblackwell" class="hnuser">jwblackwell</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22334290">2 hours ago</a></span> <span id="unv_22334290"></span> | <a href="https://news.ycombinator.com/hide?id=22334290&amp;auth=6b49e642011c91dfcb2710541073f2657e54baa4&amp;goto=news" onclick="return hidestory(event, this, 22334290)">hide</a> | <a href="https://news.ycombinator.com/item?id=22334290">14&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22333664">
      <td align="right" valign="top" class="title"><span class="rank">9.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22333664" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22333664&amp;how=up&amp;auth=6d04839562760c1902f4315319254c0f51c0bc1b&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://cpldcpu.wordpress.com/2020/02/14/what-made-the-cdc6600-fast/" class="storylink">What made the 1960s CDC6600 supercomputer fast?</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=cpldcpu.wordpress.com"><span class="sitestr">cpldcpu.wordpress.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22333664">70 points</span> by <a href="https://news.ycombinator.com/user?id=kken" class="hnuser">kken</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22333664">6 hours ago</a></span> <span id="unv_22333664"></span> | <a href="https://news.ycombinator.com/hide?id=22333664&amp;auth=6d04839562760c1902f4315319254c0f51c0bc1b&amp;goto=news" onclick="return hidestory(event, this, 22333664)">hide</a> | <a href="https://news.ycombinator.com/item?id=22333664">11&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22325720">
      <td align="right" valign="top" class="title"><span class="rank">10.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22325720" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22325720&amp;how=up&amp;auth=09bf9a0bf91bd2e1171604bf50ec812837e1e9dd&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://ivanceras.github.io/svgbob-editor/" class="storylink">Svgbob – convert ASCII diagrams to SVG, now with styling support</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=ivanceras.github.io"><span class="sitestr">ivanceras.github.io</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22325720">102 points</span> by <a href="https://news.ycombinator.com/user?id=ivanceras" class="hnuser">ivanceras</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22325720">8 hours ago</a></span> <span id="unv_22325720"></span> | <a href="https://news.ycombinator.com/hide?id=22325720&amp;auth=09bf9a0bf91bd2e1171604bf50ec812837e1e9dd&amp;goto=news" onclick="return hidestory(event, this, 22325720)">hide</a> | <a href="https://news.ycombinator.com/item?id=22325720">18&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22326035">
      <td align="right" valign="top" class="title"><span class="rank">11.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22326035" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22326035&amp;how=up&amp;auth=694d382e42eadfe26594089919ae30c4ed681833&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://www.npmjs.com/package/micro-aws-lambda" class="storylink">A 7KB AWS lambda Node.js library with zero runtime dependencies</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=npmjs.com"><span class="sitestr">npmjs.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22326035">23 points</span> by <a href="https://news.ycombinator.com/user?id=albertgao" class="hnuser">albertgao</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22326035">4 hours ago</a></span> <span id="unv_22326035"></span> | <a href="https://news.ycombinator.com/hide?id=22326035&amp;auth=694d382e42eadfe26594089919ae30c4ed681833&amp;goto=news" onclick="return hidestory(event, this, 22326035)">hide</a> | <a href="https://news.ycombinator.com/item?id=22326035">11&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22331804">
      <td align="right" valign="top" class="title"><span class="rank">12.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22331804" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22331804&amp;how=up&amp;auth=c9636b1b4837c821504f55815915a6e244c192fd&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://www.jarednelsen.dev/posts/The-horrifically-dystopian-world-of-software-engineering-interviews" class="storylink">The dystopian world of software engineering interviews</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=jarednelsen.dev"><span class="sitestr">jarednelsen.dev</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22331804">660 points</span> by <a href="https://news.ycombinator.com/user?id=asangha" class="hnuser">asangha</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22331804">12 hours ago</a></span> <span id="unv_22331804"></span> | <a href="https://news.ycombinator.com/hide?id=22331804&amp;auth=c9636b1b4837c821504f55815915a6e244c192fd&amp;goto=news" onclick="return hidestory(event, this, 22331804)">hide</a> | <a href="https://news.ycombinator.com/item?id=22331804">555&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22331339">
      <td align="right" valign="top" class="title"><span class="rank">13.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22331339" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22331339&amp;how=up&amp;auth=6334c9d0fefd1c6cc07076f20a4026793c71cda5&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://techcrunch.com/2020/02/14/hq-trivia-shuts-down/" class="storylink">HQ Trivia shuts down after acquisition falls through</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=techcrunch.com"><span class="sitestr">techcrunch.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22331339">158 points</span> by <a href="https://news.ycombinator.com/user?id=klinskyc" class="hnuser">klinskyc</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22331339">13 hours ago</a></span> <span id="unv_22331339"></span> | <a href="https://news.ycombinator.com/hide?id=22331339&amp;auth=6334c9d0fefd1c6cc07076f20a4026793c71cda5&amp;goto=news" onclick="return hidestory(event, this, 22331339)">hide</a> | <a href="https://news.ycombinator.com/item?id=22331339">85&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22332133">
      <td align="right" valign="top" class="title"><span class="rank">14.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22332133" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22332133&amp;how=up&amp;auth=bb1cc568b1d54eabe05738faa608e4d335860fc4&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://www.cbc.ca/news/canada/toronto/rcmp-cra-telephone-scam-fraud-investigation-1.5463838" class="storylink">RCMP arrest 'money mules' tied to scam calls from India</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=cbc.ca"><span class="sitestr">cbc.ca</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22332133">97 points</span> by <a href="https://news.ycombinator.com/user?id=the_unknown" class="hnuser">the_unknown</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22332133">11 hours ago</a></span> <span id="unv_22332133"></span> | <a href="https://news.ycombinator.com/hide?id=22332133&amp;auth=bb1cc568b1d54eabe05738faa608e4d335860fc4&amp;goto=news" onclick="return hidestory(event, this, 22332133)">hide</a> | <a href="https://news.ycombinator.com/item?id=22332133">43&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22334430">
      <td align="right" valign="top" class="title"><span class="rank">15.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22334430" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22334430&amp;how=up&amp;auth=aca6779c45e7a4b98bdf3a3763d9f127ab2ac36a&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="http://www.phrack.org/papers/emulating_hypervisors_samsung_rkp.html" class="storylink" rel="nofollow">Aris Thallas – Hypervisor Necromancy; Reanimating Kernel Protectors (2020-02-14)</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=phrack.org"><span class="sitestr">phrack.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22334430">5 points</span> by <a href="https://news.ycombinator.com/user?id=based2" class="hnuser">based2</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22334430">2 hours ago</a></span> <span id="unv_22334430"></span> | <a href="https://news.ycombinator.com/hide?id=22334430&amp;auth=aca6779c45e7a4b98bdf3a3763d9f127ab2ac36a&amp;goto=news" onclick="return hidestory(event, this, 22334430)">hide</a> | <a href="https://news.ycombinator.com/item?id=22334430">discuss</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22325767">
      <td align="right" valign="top" class="title"><span class="rank">16.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22325767" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22325767&amp;how=up&amp;auth=afea1464ff23f7f19cfefabccd570e4b02aaa7a2&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://www.voorhoede.nl/en/blog/exploring-the-web-speech-api/" class="storylink">Exploring the Web Speech API</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=voorhoede.nl"><span class="sitestr">voorhoede.nl</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22325767">35 points</span> by <a href="https://news.ycombinator.com/user?id=jbmoelker" class="hnuser">jbmoelker</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22325767">6 hours ago</a></span> <span id="unv_22325767"></span> | <a href="https://news.ycombinator.com/hide?id=22325767&amp;auth=afea1464ff23f7f19cfefabccd570e4b02aaa7a2&amp;goto=news" onclick="return hidestory(event, this, 22325767)">hide</a> | <a href="https://news.ycombinator.com/item?id=22325767">4&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22325389">
      <td align="right" valign="top" class="title"><span class="rank">17.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22325389" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22325389&amp;how=up&amp;auth=2f34af4e06e476ebe63f2620490530820de673b0&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://github.com/Checksum/critic.sh" class="storylink" rel="nofollow">Show HN: Critic.sh – Dead simple testing framework for Bash</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=github.com"><span class="sitestr">github.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22325389">6 points</span> by <a href="https://news.ycombinator.com/user?id=Karupan" class="hnuser">Karupan</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22325389">2 hours ago</a></span> <span id="unv_22325389"></span> | <a href="https://news.ycombinator.com/hide?id=22325389&amp;auth=2f34af4e06e476ebe63f2620490530820de673b0&amp;goto=news" onclick="return hidestory(event, this, 22325389)">hide</a> | <a href="https://news.ycombinator.com/item?id=22325389">2&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22324836">
      <td align="right" valign="top" class="title"><span class="rank">18.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22324836" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22324836&amp;how=up&amp;auth=a32070ef89ba479df5455280537fadd6b468d051&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://blog.plover.com/math/logic/lk.html" class="storylink">Gentzen's Rules for Natural Deduction</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=plover.com"><span class="sitestr">plover.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22324836">21 points</span> by <a href="https://news.ycombinator.com/user?id=weinzierl" class="hnuser">weinzierl</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22324836">5 hours ago</a></span> <span id="unv_22324836"></span> | <a href="https://news.ycombinator.com/hide?id=22324836&amp;auth=a32070ef89ba479df5455280537fadd6b468d051&amp;goto=news" onclick="return hidestory(event, this, 22324836)">hide</a> | <a href="https://news.ycombinator.com/item?id=22324836">5&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22333563">
      <td align="right" valign="top" class="title"><span class="rank">19.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22333563" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22333563&amp;how=up&amp;auth=2976d5068db33d50c6ee79e5f60b7ee50c754333&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://rhsfinancial.com/2020/02/12/future-fossil-fuels-collapse/" class="storylink">The Future of Fossil Fuels</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=rhsfinancial.com"><span class="sitestr">rhsfinancial.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22333563">28 points</span> by <a href="https://news.ycombinator.com/user?id=apsec112" class="hnuser">apsec112</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22333563">6 hours ago</a></span> <span id="unv_22333563"></span> | <a href="https://news.ycombinator.com/hide?id=22333563&amp;auth=2976d5068db33d50c6ee79e5f60b7ee50c754333&amp;goto=news" onclick="return hidestory(event, this, 22333563)">hide</a> | <a href="https://news.ycombinator.com/item?id=22333563">31&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22327467">
      <td align="right" valign="top" class="title"><span class="rank">20.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22327467" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22327467&amp;how=up&amp;auth=4f7d6e714069de96196e2e265c3f0c8ed8bb7f46&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://www.stavros.io/posts/make-pcbs-at-home/" class="storylink">I made my own PCBs with a 3D printer</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=stavros.io"><span class="sitestr">stavros.io</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22327467">191 points</span> by <a href="https://news.ycombinator.com/user?id=StavrosK" class="hnuser">StavrosK</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22327467">20 hours ago</a></span> <span id="unv_22327467"></span> | <a href="https://news.ycombinator.com/hide?id=22327467&amp;auth=4f7d6e714069de96196e2e265c3f0c8ed8bb7f46&amp;goto=news" onclick="return hidestory(event, this, 22327467)">hide</a> | <a href="https://news.ycombinator.com/item?id=22327467">120&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22334310">
      <td align="right" valign="top" class="title"><span class="rank">21.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22334310" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22334310&amp;how=up&amp;auth=aa176d112488a197a6fdfc5ef7dcd674bbdc7715&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://medium.com/@animeshgaitonde/how-https-works-part-1-building-blocks-64f9915b1f39" class="storylink">How HTTPS works – Explained in layman terms</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=medium.com"><span class="sitestr">medium.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22334310">22 points</span> by <a href="https://news.ycombinator.com/user?id=animeshg" class="hnuser">animeshg</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22334310">2 hours ago</a></span> <span id="unv_22334310"></span> | <a href="https://news.ycombinator.com/hide?id=22334310&amp;auth=aa176d112488a197a6fdfc5ef7dcd674bbdc7715&amp;goto=news" onclick="return hidestory(event, this, 22334310)">hide</a> | <a href="https://news.ycombinator.com/item?id=22334310">4&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22324216">
      <td align="right" valign="top" class="title"><span class="rank">22.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22324216" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22324216&amp;how=up&amp;auth=5a22c5148af78c7ea173ce8594bec48dff8a1655&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://science.sciencemag.org/content/early/2020/02/12/science.aay3999" class="storylink">The geology and geophysics of Kuiper Belt object (486958) Arrokoth</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=sciencemag.org"><span class="sitestr">sciencemag.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22324216">23 points</span> by <a href="https://news.ycombinator.com/user?id=robin_reala" class="hnuser">robin_reala</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22324216">7 hours ago</a></span> <span id="unv_22324216"></span> | <a href="https://news.ycombinator.com/hide?id=22324216&amp;auth=5a22c5148af78c7ea173ce8594bec48dff8a1655&amp;goto=news" onclick="return hidestory(event, this, 22324216)">hide</a> | <a href="https://news.ycombinator.com/item?id=22324216">2&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22332891">
      <td align="right" valign="top" class="title"><span class="rank">23.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22332891" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22332891&amp;how=up&amp;auth=dced4e1245ba15425ecdcc99d58b85f9aacfdaff&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://condor.depaul.edu/~mfiddler/hyphen/humunivers.htm" class="storylink">Human Universals (2002)</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=depaul.edu"><span class="sitestr">depaul.edu</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22332891">33 points</span> by <a href="https://news.ycombinator.com/user?id=jelliclesfarm" class="hnuser">jelliclesfarm</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22332891">9 hours ago</a></span> <span id="unv_22332891"></span> | <a href="https://news.ycombinator.com/hide?id=22332891&amp;auth=dced4e1245ba15425ecdcc99d58b85f9aacfdaff&amp;goto=news" onclick="return hidestory(event, this, 22332891)">hide</a> | <a href="https://news.ycombinator.com/item?id=22332891">7&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22331188">
      <td align="right" valign="top" class="title"><span class="rank">24.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22331188" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22331188&amp;how=up&amp;auth=5bfd493ff74fb35cd67b9102dad72818ebcbac7e&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://medium.com/@cazzer/designing-the-most-performant-row-level-security-strategy-in-postgres-a06084f31945" class="storylink">Designing the most performant row-level security schema in Postgres (2018)</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=medium.com"><span class="sitestr">medium.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22331188">55 points</span> by <a href="https://news.ycombinator.com/user?id=dfee" class="hnuser">dfee</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22331188">13 hours ago</a></span> <span id="unv_22331188"></span> | <a href="https://news.ycombinator.com/hide?id=22331188&amp;auth=5bfd493ff74fb35cd67b9102dad72818ebcbac7e&amp;goto=news" onclick="return hidestory(event, this, 22331188)">hide</a> | <a href="https://news.ycombinator.com/item?id=22331188">5&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22333444">
      <td align="right" valign="top" class="title"><span class="rank">25.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22333444" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22333444&amp;how=up&amp;auth=c670343b8ef384353c988eab38c7a633d6f45a79&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://www.bloomberg.com/graphics/startup-barometer/" class="storylink">Bloomberg U.S. Startups Barometer</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=bloomberg.com"><span class="sitestr">bloomberg.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22333444">72 points</span> by <a href="https://news.ycombinator.com/user?id=elsewhen" class="hnuser">elsewhen</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22333444">6 hours ago</a></span> <span id="unv_22333444"></span> | <a href="https://news.ycombinator.com/hide?id=22333444&amp;auth=c670343b8ef384353c988eab38c7a633d6f45a79&amp;goto=news" onclick="return hidestory(event, this, 22333444)">hide</a> | <a href="https://news.ycombinator.com/item?id=22333444">24&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22328822">
      <td align="right" valign="top" class="title"><span class="rank">26.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22328822" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22328822&amp;how=up&amp;auth=aecec3a1797573d6f88e5797b141ac9924cb6acf&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://cache.edge.apple/" class="storylink">Apple Edge Cache</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=edge.apple"><span class="sitestr">edge.apple</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22328822">443 points</span> by <a href="https://news.ycombinator.com/user?id=bwilliams18" class="hnuser">bwilliams18</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22328822">18 hours ago</a></span> <span id="unv_22328822"></span> | <a href="https://news.ycombinator.com/hide?id=22328822&amp;auth=aecec3a1797573d6f88e5797b141ac9924cb6acf&amp;goto=news" onclick="return hidestory(event, this, 22328822)">hide</a> | <a href="https://news.ycombinator.com/item?id=22328822">188&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22326731">
      <td align="right" valign="top" class="title"><span class="rank">27.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22326731" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22326731&amp;how=up&amp;auth=86abc74af3da85b6640a35ae70387ed73c960a92&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://www.wired.com/story/signal-encrypted-messaging-features-mainstream/" class="storylink">Signal is finally bringing its secure messaging to the masses</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=wired.com"><span class="sitestr">wired.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22326731">514 points</span> by <a href="https://news.ycombinator.com/user?id=jmsflknr" class="hnuser">jmsflknr</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22326731">22 hours ago</a></span> <span id="unv_22326731"></span> | <a href="https://news.ycombinator.com/hide?id=22326731&amp;auth=86abc74af3da85b6640a35ae70387ed73c960a92&amp;goto=news" onclick="return hidestory(event, this, 22326731)">hide</a> | <a href="https://news.ycombinator.com/item?id=22326731">322&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22328516">
      <td align="right" valign="top" class="title"><span class="rank">28.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22328516" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22328516&amp;how=up&amp;auth=adde0009a37c265f658bf10c3447b657f7adaea3&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://www.quantamagazine.org/the-map-of-mathematics-20200213/" class="storylink">A Map of Mathematics</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=quantamagazine.org"><span class="sitestr">quantamagazine.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22328516">340 points</span> by <a href="https://news.ycombinator.com/user?id=theafh" class="hnuser">theafh</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22328516">18 hours ago</a></span> <span id="unv_22328516"></span> | <a href="https://news.ycombinator.com/hide?id=22328516&amp;auth=adde0009a37c265f658bf10c3447b657f7adaea3&amp;goto=news" onclick="return hidestory(event, this, 22328516)">hide</a> | <a href="https://news.ycombinator.com/item?id=22328516">49&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22333923">
      <td align="right" valign="top" class="title"><span class="rank">29.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22333923" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22333923&amp;how=up&amp;auth=fd4a6da4fb7b61790c6b4a2c64f338e496e343cc&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="http://www.langston.com/SVM.html" class="storylink" rel="nofollow">Eedie and Eddie on the Wire (1985)</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=langston.com"><span class="sitestr">langston.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22333923">4 points</span> by <a href="https://news.ycombinator.com/user?id=kick" class="hnuser">kick</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22333923">3 hours ago</a></span> <span id="unv_22333923"></span> | <a href="https://news.ycombinator.com/hide?id=22333923&amp;auth=fd4a6da4fb7b61790c6b4a2c64f338e496e343cc&amp;goto=news" onclick="return hidestory(event, this, 22333923)">hide</a> | <a href="https://news.ycombinator.com/item?id=22333923">1&nbsp;comment</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class="athing" id="22328616">
      <td align="right" valign="top" class="title"><span class="rank">30.</span></td>      <td valign="top" class="votelinks"><center><a id="up_22328616" onclick="return vote(event, this, &quot;up&quot;)" href="https://news.ycombinator.com/vote?id=22328616&amp;how=up&amp;auth=2e6bb6c244655927542d3f59f67d1b6146cad637&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://www.nytimes.com/2020/02/13/business/economy/housing-crisis-conor-dougherty-golden-gates.html" class="storylink">California’s housing crisis: how a bureaucrat pushed to build</a><span class="sitebit comhead"> (<a href="https://news.ycombinator.com/from?site=nytimes.com"><span class="sitestr">nytimes.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_22328616">300 points</span> by <a href="https://news.ycombinator.com/user?id=danso" class="hnuser">danso</a> <span class="age"><a href="https://news.ycombinator.com/item?id=22328616">18 hours ago</a></span> <span id="unv_22328616"></span> | <a href="https://news.ycombinator.com/hide?id=22328616&amp;auth=2e6bb6c244655927542d3f59f67d1b6146cad637&amp;goto=news" onclick="return hidestory(event, this, 22328616)">hide</a> | <a href="https://news.ycombinator.com/item?id=22328616">572&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
            <tr class="morespace" style="height:10px"></tr><tr><td colspan="2"></td><td class="title"><a href="https://news.ycombinator.com/news?p=2" class="morelink" rel="next">More</a></td></tr>
  </tbody></table>
</td></tr>
<tr><td><img src="./Hacker News_files/s.gif" height="10" width="0"><table width="100%" cellspacing="0" cellpadding="1"><tbody><tr><td bgcolor="#ff6600"></td></tr></tbody></table><br><center><a href="https://www.ycombinator.com/apply/">
        Applications are open for YC Summer 2020
      </a></center><br><center><span class="yclinks"><a href="https://news.ycombinator.com/newsguidelines.html">Guidelines</a>
        | <a href="https://news.ycombinator.com/newsfaq.html">FAQ</a>
        | <a href="mailto:hn@ycombinator.com">Support</a>
        | <a href="https://github.com/HackerNews/API">API</a>
        | <a href="https://news.ycombinator.com/security.html">Security</a>
        | <a href="https://news.ycombinator.com/lists">Lists</a>
        | <a href="https://news.ycombinator.com/bookmarklet.html" rel="nofollow">Bookmarklet</a>
        | <a href="http://www.ycombinator.com/legal/">Legal</a>
        | <a href="http://www.ycombinator.com/apply/">Apply to YC</a>
        | <a href="mailto:hn@ycombinator.com">Contact</a></span><br><br><form method="get" action="https://hn.algolia.com/">Search:
          <input type="text" name="q" value="" size="17" autocorrect="off" spellcheck="false" autocapitalize="off" autocomplete="false"></form>
            </center></td></tr>
      </tbody></table></center><script type="text/javascript" src="./Hacker News_files/hn.js"></script>
</body></html>`;
